services:
  - type: web
    name: szerotwo002bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7175283426:AAFLsjVA3lP8QhVx5r4uHDKA94UuTK0THaI
      - key: TELEGRAM_CHAT_ID
        value: -1002652115660
